dist: bionic
language: java

sudo: required

jdk:
  - openjdk8
#  - openjdk11

install: true

cache:
  directories:
    - $HOME/.m2

script:
  - java -version
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B -Dsonar.projectKey=AxonFramework_extension-kafka
  - JAVA_HOME=$(dirname ${JAVA_HOME})/openjdk11 ${JAVA_HOME}/bin/java -version
  - JAVA_HOME=$(dirname ${JAVA_HOME})/openjdk11 mvn clean verify -B

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "VoVcx2wRdxNjMyvpJjZniXvXTK4fMJT7tFcP6JHjKsiwOrpBjt3E5W1FNgKsdh08TNFUc0A9QYxWB0ZXS+bV/iHVvYDiL/gdtyObQalLtdSk2d7LsBw1W0RmVbfMIv91u6a3uWsWyeDev87p4Srlh+frD5wh1zYlhBClhMkeZIyIJzge3xxFtJuHtYxt/h/VNl0gStR0y6D7ZNMr40UD0GqX2x2n1e+HuD5BT65VrYiA26cU2CVminbRQKwDedUw37MqjOmLxSDXaXBb7foszAvbGEQjR0CWkOoKQEDtMeP1wLgWxz6QhTFurCNW5TN7vZBSRjp4yfPqwpOkFDH09TSTb9jjHPhlhxtfj+Gca2X73QWvk5cZVPRJ90xjc+5P4iu7njhg70THUKFCqyKRWi2hHBvpIuF0q4h8WUWFakDtxfLf0g6UXS0Ovz+JgRC8SyhJ5gxGeS+d+5X7eZbFgnbx45OF+XBdnwnO6Iq6fFJQuhzix/vml00BAEFmOX6sg2QFhdT7On/5H8YIltZf+HpLJgZPFlFVfkActVtIn3mJ8gnpVLHuCWWi9s3q6J27EXf+30AUWO3Zc+h6r4+vJcK6rtY1rK0I1D3ZhR3sAtQG8lz4AmaWEUOvxyAM9KylM/vzqfbP9ZJVMlAxmHLrd6hqD/cyHyR/I20XJ7NHGSw="