spring:
  application:
    name: KafkaAxonExample

axon:
  axonserver:
    enabled: false
  kafka:
    clientid: kafka-axon-example
    producer:
      retries: 0
      bootstrapservers: localhost:9092

    properties:
      security.protocol: PLAINTEXT
