spring:
  application:
    name: KafkaAxonExample

axon:
  axonserver:
    enabled: false
  serializer:
    events: jackson
  kafka:
    clientid: kafka-axon-example
    producer:
      retries: 0
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092

    properties:
      security.protocol: PLAINTEXT
